### ISSUE TITLE
Create a user manual for Jcd.Units

### ISSUE THREAD

**Issue by jason-c-daniels** [jason-c-daniels/Jcd.Units#8]
### Task Description

Write a user manual that walks a programmer through using Jcd.Units.

### Acceptance Criteria

The user manual must:

- [ ] State the purpose for creating this library.
  - [ ] Type safe unit-type aware SIMPLE quantities with auto-conversion within the same domain.
  - [ ] Simplify the conversion process.
  - [ ] Provide unobtrusive syntactic sugar for conversion process.
- [ ] Explain simple usage of existing units with the Quantity class and its extension methods.
  - [ ] Explain how to use units of measure via the static instance variables.
  - [ ] Explain what the UnitRegistry is and how to use it to auto-register built-in units.
  - [ ] Explain how to use units of measure once registered in the UnitRegistry.
- [ ] Explain advanced usage of existing units.
  - [ ] Calling the Quantity constructor
  - [ ] Registering a built-in or custom double comparers for various reasons.
    - [ ] Global vs type specific registration. Provide use cases for type specific.
    - [ ] Threading concerns with comparison registration.
    - [ ] General concerns with changing double comparison methods mid-stream, regardless if from other threads.
    - [ ] Provide example workarounds.
  - [ ] Explain how to correctly create custom units of measure by hand coding.
    - [ ] Explain the concepts of _Fundamental Unit of Measure_ vs _Base Unit of Measure_ as implemented by this library.
    - [ ] Explain what is required for creating a UnitOfMeasure derived class.
    - [ ] Explain how to register individual UnitOfMeasure instances with the UnitRegistry.
- [ ] Give guidance on various items.
  - [ ] Explain that, while some default numeric formatting is provided, it is not localized and localization is the consumers concern.
  - [ ] Transforming derived units of measure into a simple representation that can be handled by Jcd.Units.
  - [ ] The user should never try to redefine the fundamental base unit for built-in units of measure.
- [ ] Explain and quantify the limitations of the system.
  - [ ] Default double comparison limitations and methods. List built-in comparers.
  - [ ] Rounding errors due to double arithmetic. Cite the need to use sub 15-digit comparers in unit tests.
  - [ ] Inability to correctly infer derived units (e.g. multiply by 0.1 vs divide by 10, numerically equivalent, and without context no way for the library to know the intent,     synthesize a derived unit, or strip units entirely.) Give examples.
  - [ ] Unit selection during operations. Customizing. Built-in alternate methods.
- [ ] Performance considerations
  - [ ] Unit autoregistration is slow, uses reflection, and should only be done once.
  - [ ] Manual registration is only faster if it's seldom done (lookups get rebuilt on next access, batch registrations, or do on app startup)
  - [ ] Doubles are slow. A unit of measure conversion library on top of them is possibly orders of magnitude slower.
  - [ ] Use raw doubles (or ints if appropriate); in the heart of an algorithm, only converting units on the in and out.
  - [ ] How to be somewhat unit agnostic while still improving performance over defaults. (Only perform ops on like unit representation, though this is hardly different from convert to target unit on input and doing integral data type operations and converting on output.)
- [ ] Basic command-line usage and current limitations of `unit-gen.exe`
  - [ ] can currently only generate units for Jcd.Units, this will change.
  - [ ] needs to run inside of the Jcd.Units folder to run, this will change.

### Motivation

To better enable users to correctly use the library and associated tools (UnitGen.csproj)

### Additional Context

Large and/or complex libraries seldom see much use when there is only per-call API documentation. Training material helps in education and adoption of use. As well, if a use case is not well suited for using a library, potential (erroneous) users need sufficient information to understand if their use case is one the library will actually address.
